### ISSUE TITLE
[Issue to be fixed] Support for the TorchMaster mod for the FTB OceanBlock pack

### ISSUE THREAD

**Issue by mcdodge34** [ThePaul-T/WYML#10]
Right now according to my research, WYML does something that prevent the mod TorchMaster from preventing mob spawning correctly, its not something the mod author can change on his side see here https://github.com/Xalcon/TorchMaster/issues/165 and it was confirmed once WYML is removed from FTB OceanBlock the TorchMaster starts to work like it should and prevent mob spawning in a big radius (usually 64 blocks around the TorchMaster location). Please can you do something about this.

**Comment by ThePaul-T** [comment]
Should be fixed in the latest version, was a silly mistake when implementing the hook, just used the player's eye height instead of the block.
