### ISSUE TITLE
Upgrading from 1.08 to 1.09 on an existing world doesn't work

### ISSUE THREAD

**Issue by Porcy** [ThePaul-T/WYML#11]
Server simply won't start...
[crash-2021-11-20_15.27.13-server.txt](https://github.com/ThePaul-T/WYML/files/7575196/crash-2021-11-20_15.27.13-server.txt)

**Comment by ThePaul-T** [comment]
Try http://transfer.ch.tools/OsuI0/wyml-1.1.0-PR1-forge.jar

All my testing was on systems with best-of-class M.2 SSD's with only a couple of mods, the time seemed completely negligible there but that was a mistake.

This should thread the config generation, once confirmed fixed, I will upload to curseforge as release not beta.

**Comment by Porcy** [comment]
Works like a charm :)
Finally some peace with a Mega Torch and cursed earth still works.
