### ISSUE TITLE
Uncompatible With Enhancedcelestials

### ISSUE THREAD

**Issue by SeanChengN** [ThePaul-T/WYML#12]
architectury-1.24.35-forge
enhancedcelestials-2.0.9-1.16.5
wyml-1.1.0-forge

Can start the game, but crashes when entering the world.
Can it be compatible by modifying the config?
[crash-2021-11-23_11.29.05-server.txt](https://github.com/ThePaul-T/WYML/files/7585682/crash-2021-11-23_11.29.05-server.txt)

**Comment by gigabit101** [comment]
Fixed in 1.1.1
