### ISSUE TITLE
Overrides Torchmaster Mega Torch

### ISSUE THREAD

**Issue by Elfinslayer** [ThePaul-T/WYML#13]
This mod seems to override the Torchmaster Mega Torch mod. An example is in the latest FTB Oceanblock modpack, you can place the Mega Torch down in a dark area and back up enough for mobs to spawn. When this mod is removed/disabled from the pack the Mega Torch works correctly.

**Comment by gigabit101** [comment]
Update to the latest version of the Mod, This issue should be resolved, The issue was that we passed the wrong Z blockpos to Forges event https://www.curseforge.com/minecraft/mc-mods/wyml/files/3535933

**Comment by gigabit101** [comment]
This issue has been set to fixed on the linked repo, Closing
