### ISSUE TITLE
Floating entities won't pick up [MC 1.16.5] [Forge] [Mod conflict]

### ISSUE THREAD

**Issue by MysticAura** [ThePaul-T/WYML#14]
java version: 1.8.0_241
mc version: 1.16.5
forge 36.2.19
wyml-1.1.1-forge.jar
architectury-1.25.36.jar
performant-1.16.2-5-3.77m.jar

**What happens:**

Floating entities don't go into your inventory.

**What should happen:**

Entity pickup.

**Oddity:**

If there is already a floating entity when you enter the game, that will go into your inventory (just nothing newly created)

**Steps to reproduce:**

Load game with the above mods installed
Drop or break anything which results in floating entities.
Stare sadly at the unattainable items.

[debug.log](https://github.com/ThePaul-T/WYML/files/7672439/debug.log)
[latest.log](https://github.com/ThePaul-T/WYML/files/7672441/latest.log)

Edit: Just to answer this question ahead of time... I tested this at spawn and 200 blocks away. Same results.

**Comment by gigabit101** [comment]
This was fixed in a previous version of the mod, please update
