### ISSUE TITLE
Should be Server only - 1.1.4 forge - Currently required on Client as well as dedicated Server 

### ISSUE THREAD

**Issue by mjevans** [ThePaul-T/WYML#26]
When WhyYouMakeLag is installed on the server clients that lack it are unable to connect to the server.

"Failed to connect to the server" "Failed to synchronize registry data from server, closing connection" "Your client is missing the following mods, install these mods to join this server:" ... WhyYouMakeLag 1.1.4

Is there a true need for the clients to also have this mod?  If it isn't shipped with a mod pack it can be a real hardship for less technical users to modify a mod pack.  Worse if it's also installed on end user machines does the config need to be provided as well?  That moves the goal posts from actual hardship to likely never worth doing.

**Comment by gigabit101** [comment]
The mod is required client-side as well as on the server due to the paper bags that need to be registered on the client as well as the server
