### ISSUE TITLE
Sudden TPS lag from WYMLRandom.get() exceptions

### ISSUE THREAD

**Issue by legitswitch** [ThePaul-T/WYML#5]
### Modpack

FTB OceanBlock

### Modpack version

1.3

### Log Files

https://spark.lucko.me/NPNruWhWhB

### Describe the bug

TPS has decreased quite a bit due to WYML mod encountering exceptions upon calling the WYMLRandom.get() method. Perhaps this method could be optimized? Or maybe for some reason WYMLRandom is being called a lot more than usual?

### Steps to reproduce

Not sure, I think I noticed it started happening after using inControl mod to block spawns of squids, then removing it. I could provide a world download.

### Expected behaviour

TPS would be higher for the amount of players but now is noticeably lower.

### Screenshots

![image](https://user-images.githubusercontent.com/88232383/137349344-aecec52f-f0b4-4f12-94b8-62f37513e8a4.png)

### Additional information

https://github.com/ThePaul-T/WYML/blob/2185c3905ca860235289ad49abf7713fe257a087/common/src/main/java/net/creeperhost/wyml/WYMLRandom.java#L13-L35

**Comment by ThePaul-T** [comment]
Good catch.

This code should not exist anymore, I'll ensure the whole class is removed so a mistake like this can't happen again.

We experimented with moving Randoms to a thread when they're called a lot and pre-generating them, the overhead of the thread, basically matched any performance increase so it just causes complexity for no reason.

This will be removed asap.
