### ISSUE TITLE
[1.16.5] [forge] Add compat with Untamed Wilds spawn - WYML doesn't handle it well.

### ISSUE THREAD

**Issue by Cixon** [ThePaul-T/WYML#7]
For a while now **[untamed wilds](https://www.curseforge.com/minecraft/mc-mods/untamedwilds)** has had an issue with stabilizing their entity count. Recently the dev have done a bit better job with it but it still struggles on the server side and I would love if WYML could be more compatible with it!

The reason I'd love if WYML could take care of untamed wilds spawn is for various reasons but mainly because I love how well WYML does its job. The ticket on their github [#4](https://github.com/RayTrace082/untamedwilds/issues/4) was posted months ago and still has not had a solution for it since.

I've also taken the time to list all the mob ids so it could hopefully be a bit easier for the WYML team to address this issue and hopefully add better compat for it? Best regards, Cixon!

### mob ids:
**WATER_AMBIENT(s)**
untamedwilds:aardvark
untamedwilds:arowana
untamedwilds:football_fish
untamedwilds:giant_clam
untamedwilds:giant_salamander
untamedwilds:shark
untamedwilds:softshell_turtle
untamedwilds:sunfish
untamedwilds:trevally

**AMBIENT_CREATURE(s)**
untamedwilds:bear_black
untamedwilds:bear_blind
untamedwilds:bear_brown
untamedwilds:bear_cave
untamedwilds:bear_panda
untamedwilds:bear_polar
untamedwilds:bear_spectacled
untamedwilds:bear_sun
untamedwilds:bigcat_cave_lion
untamedwilds:bigcat_jaguar
untamedwilds:bigcat_leopard
untamedwilds:bigcat_lion
untamedwilds:bigcat_marsupial_lion
untamedwilds:bigcat_puma
untamedwilds:bigcat_snow_leopard
untamedwilds:bigcat_tiger
untamedwilds:boar
untamedwilds:hippo
untamedwilds:hyena
untamedwilds:large_snake
untamedwilds:newt
untamedwilds:rhino
untamedwilds:snake
untamedwilds:tarantula
untamedwilds:tortoise

**Comment by ThePaul-T** [comment]
We can give it a try, we was planning to do some settings per mob category, so we will probably use the issue in this mod as a test case.

**Comment by Cixon** [comment]
excellent! thank u!

**Comment by ThePaul-T** [comment]
Done something similar to what you asked, but more... Expansive.

On first world load, it'll generate configs in config/wyml-SpawnRules

Each config in there will be the name of the mod that added it.

Inside that is an object for each mob type (So say, WATER_AMBIENT
Then inside that will be an object for each mob, with a limit that is how many can spawn in a single chunk

This will, by default, do nothing.

In the main config, there is an open to tell it to respect these configs (ENABLE_PER_MOD_CONFIGS)

Once enabled, this will apply those limits to any natural spawns.

However, if for some reason whatever mod is not using natural spawns and is adding the entities directly (like mods like soul shards do) then you can enable "HARD_MOB_LIMITS", this will then intercept entity adds and apply the limits there too.

Let me know if you encounter any issues.
