### ISSUE TITLE
Enhancement Request: Add an ignore list for ITEM_DESPAWN_TIME

### ISSUE THREAD

**Issue by JustJinxed** [ThePaul-T/WYML#8]
There's some items we don't want to despawn in the world, and it seems WYML can't possibly check the multitude of ways items set themselves to not depsawn. Could you maybe add a ignore list to the config file so we can add items like Botania's mana tablet, and AE2 fluix seeds from despawning.

**Comment by ThePaul-T** [comment]
Seems like a good idea to me - I can't work on the mod at work at the moment, so this needs to wait until I have free time when at home.

**Comment by ThePaul-T** [comment]
We've both started respecting custom lifespans in forge and also added a deny list for despawning items in the latest version.
